# nixpacks.toml
[phases.setup]
# System packages only
nixPkgs = ["python311", "postgresql", "gcc", "git"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/gunicorn app:app --log-file=- --bind 0.0.0.0:$PORT"